# async, await
async, await를 사용하면 Promise의 then 메소드를 체인형식으로 호출하는 것보다 가독성이 좋아짐.
``` js
// 함수앞에 async라는 키워드를 붙여주면 Promise를 반환함.
async function getName() {
  return "Mike";
}

console.log(getName()); //Promise { 'Mike' }

getName().then((name) => {
  console.log(name);
}); // Mike
```
``` js
// 만약에 리턴값이 Promise면? 그 값을 그대로 사용함.
async function getName() {
  return Promise.resolve("Tom");
}

getName().then((name) => {
  console.log(name);
}); //Tom

// 만약에 함수내부에서 예외가 발생하면 rej 상태의 Promise가 반환됨.
async function getName() {
  throw new Error("err..");
}

getName().catch((err) => {
  console.log(err);
}); //Error: err..
```

``` js
// await 키워드는 async 함수 내부에서만 사용할 수 있음. 일반함수에서 사용하면 에러가 발생함.

function getName(name) {
  return new Promise((resolve, reject) => {
    setTimeout(() => {
      resolve(name);
    }, 1000);
  });
}

async function showName() {
  const result = await getName("Mike");
  console.log(result);
}

console.log("시작");
showName();
/* 시작 Mike
await 키워드 오른쪽에는 Promise가 오고, 그 프로미스가 처리될때까지 기다림. 이 코드는 1초후에 마이크가 찍힘, 
result에 getName에서 Result된 값을 기다렸다가 넣어주는 것 */
```
``` js
// Promise 때 예제를 async와 await 적용 시
const f1 = () => {
  return new Promise((res, rej) => {
    setTimeout(() => {
      res("1번 주문 완료");
    }, 1000);
  });
};

const f2 = (message) => {
  console.log(message);
  return new Promise((res, rej) => {
    setTimeout(() => {
      res("2번 주문 완료");
    }, 3000);
  });
};

const f3 = (message) => {
  console.log(message);
  return new Promise((res, rej) => {
    setTimeout(() => {
      res("3번 주문 완료");
    }, 2000);
  });
};

console.log("시작");
async function order() {
  const result1 = await f1();
  const result2 = await f2(result1);
  const result3 = await f3(result2);
  console.log(result3);
  console.log("종료");
}

order();
/*
f1()
  .then((res) => f2(res))
  .then((res) => f3(res))
  .then((res) => console.log(res))
  .catch(console.log); */


  /* 시작 1번 주문 완료 2번 주문 완료 3번 주문 완료 종료
  동일하게 실행 됨, 변수에 이 데이터가 기다렸다가 들어가는게 명확하게 보임,
  그래서 Promise then을 쓰는 것 보다 가독성이 좋음
  대부분의 상황에서 async await 를 쓰는 것을 선호함. */
```
``` js
// 만약에 2번을 rej으로 바꾸면?

const f1 = () => {
  return new Promise((res, rej) => {
    setTimeout(() => {
      res("1번 주문 완료");
    }, 1000);
  });
};

const f2 = (message) => {
  console.log(message);
  return new Promise((res, rej) => {
    setTimeout(() => {
      // res("2번 주문 완료");
      rej(new Error("err.."));
    }, 3000);
  });
};

const f3 = (message) => {
  console.log(message);
  return new Promise((res, rej) => {
    setTimeout(() => {
      res("3번 주문 완료");
    }, 2000);
  });
};

console.log("시작");
async function order() {
  try {
    const result1 = await f1();
    const result2 = await f2(result1);
    const result3 = await f3(result2);
    console.log(result3);
  } catch (e) {
    console.log(e);
  }
  console.log("종료");
}

order();
/*
f1()
  .then((res) => f2(res))
  .then((res) => f3(res))
  .then((res) => console.log(res))
  .catch(console.log); */

/* Error: err..
에러가 나고 코드가 멈춤, 이럴때 Promise는 catch를 써줬는데 async await 함수에서는 try catch문으로 감싸주면 됨 */
/* 시작 1번 주문 완료 Error: err.. 종료
Try catch문으로 감싸주면 에러로그를 찍고 이후 작업이 계속 진행을 함. */
```
``` js
// Promise all 사용한다면?

const f1 = () => {
  return new Promise((res, rej) => {
    setTimeout(() => {
      res("1번 주문 완료");
    }, 1000);
  });
};

const f2 = (message) => {
  console.log(message);
  return new Promise((res, rej) => {
    setTimeout(() => {
      res("2번 주문 완료");
      // rej(new Error("err.."));
    }, 3000);
  });
};

const f3 = (message) => {
  console.log(message);
  return new Promise((res, rej) => {
    setTimeout(() => {
      res("3번 주문 완료");
    }, 2000);
  });
};

console.log("시작");
async function order() {
  try {
    const result = await Promise.all([f1(), f2(), f3()]);
    console.log(result);
  } catch (e) {
    console.log(e);
  }
  console.log("종료");
}

order();
/*
f1()
  .then((res) => f2(res))
  .then((res) => f3(res))
  .then((res) => console.log(res))
  .catch(console.log); */

  /* 시작 undefined undefined [ '1번 주문 완료', '2번 주문 완료', '3번 주문 완료' ] 종료
이렇게 async await 함수 내부에서 비동기 함수를 명령으로 실행할 수 있음 */
```