# 프로미스(Promise)
new Promise로 생성함. 함수를 전달 받는데 인수는 resolve, reject임, resolve는 성공했을 때, reject는 실패했을 때 실행되는 함수임. 이렇게 어떤일이 완료된 이후 실행되는 함수를 콜백함수(callback)라고 함
``` js
const pr = new Promise((resolve, reject) => {
	// code
});
```
new Promise 생성자가 반환하는 Promise 객체는 state와 result를 property로 받음.  
state는 초기에 pending(대기)이었다가(result는 undefined상태) resolve(value)가 호출되면 fulfilled(이행됨)가 됨. 이때 result는 resolve로 전달된 값(value)임.   
만약 reject(error)가 호출되면 state는 rejected(거부됨)가 됨. 이때 result는 reject 함수로 전달된 error임.

## Promise 예시
``` js
// 판매자의 코드를 살펴봄, 판매자는 주문을 받으면 3초동안 무언가를 하고 성공인지 실패인지 알려줌
const pr = new Promise((resolve, reject) => {
	setTimeout(() =>{
		resolve('OK')
	}, 3000)
});

/* 이코드의 처음
state: pending(대기)
result : undifined */
/* 이코드의 3초(3s)후
state: fulfilled(이행됨)
result: 'OK' */

//실패를 가정한 코드
const pr = new Promise((resolve, reject) => {
	setTimeout(() => {
		reject(new Error('error...'))
	}, 3000)
});
/* 이코드의 처음
state: pending(대기)
result : undifined */
/* 이코드의 3초(3s)후
state: rejected(거부됨)
result: error */
```
``` js
// 이제 소비자의 코드를 살펴봄
const pr = new Promise((resolve, reject) => {
	setTimeout(() => {
		resolve('OK')
	}, 3000)
});

pr.then(
	function(result){}, // Promise이행 되었을때 실행되는 함수, result에는 'OK'라는 값이 들어옴 
	function(err){} // 거부 되었을때 실행하는 함수, err에는 error값이 들어감.
);
// then을 이용하여 reject와 resolve를 처리할 수 있음. 

// 작성을 하면 이런 모습이 됨

const pr = new Promise((resolve, reject) => {
	setTimeout(() => {
		resolve('OK')
	}, 3000)
});

pr.then(
	function(result){
		console.log(result + ' 가지러 가자. ');
	},
	function(err){
		console.log('다시 주문해주세요.');
	}
);
// resolve로 실행되었기 떄문에 이상황에서 2번째 콜백은 실행되지 않음
```
then 이 외에 사용할 수 있는 것은 catch와 finally입니다. catch는 에러가 발생한 경우, 즉 reject인 경우에만 실행 됨
``` js
pr.then(
	function(result){},
	function(err){}
);
// 상기 코드를 하기와 같이 바꿀 수 있음
pr.then(
	function(result){}
).catch(
	function(err){}
)
// 두번째 전달하는 함수를 catch안으로 넣어주는 것, 동일하게 동작함. 그런게 이렇게 catch로 명확하게 구분해 주는 게 가독성이 좋고, 이런 경우 첫번째 함수를 실행했다가 나는 에러도 잡아줄 수 있기 떄문에 catch문을 사용하는 것이 훨씬 좋음
```
finally는 이행이든 거부든 처리가 완료되면 항상 처리됨. 로딩화면 같은 것을 없앨 때 사용 됨
``` js
pr.then(
	function(result){}
).catch(
	function(err){}
).finally(
	function(){
		console.log('--- 주문 끝 ---')
	}
)
```

## 실전 예제
``` js
// resolve 
const pr = new Promise((resolve, reject) => {
  setTimeout(() => {
    resolve('OK');
  }, 1000);
});

console.log("시작");
pr.then((result) => {
  console.log(result);
})

  .catch((err) => {
    console.log(err);
})
  .finally(()=> {
    console.log("끝");
});

시작
Promise {<pending>}
VM74:9 OK
VM74:16 끝
// 시작이 나오고 1초 이후 OK와 끝이 나옴

// reject
const pr = new Promise((resolve, reject) => {
  setTimeout(() => {
    reject(new Error("err..."));
  }, 1000);
});

console.log("시작");
pr.then((result) => {
  console.log(result);
})

  .catch((err) => {
    console.log(err);
})
  .finally(()=> {
    console.log("끝");
});

시작
Promise {<pending>}
VM77:13 Error: err...
    at <anonymous>:3:12
VM77:16 끝
// 시작이 나오고 1초 이후 err와 끝이 나옴
// 이행과 거부에 관계없이 끝이라는 로그는 항상 뜸
```
``` js
// Promise를 사용하지 않는 버전 
const f1 = (callback) => {
  setTimeout(function () {
    console.log("1번 주문 완료");
    callback();
  }, 1000);
};

const f2 = (callback) => {
  setTimeout(function () {
    console.log("2번 주문 완료");
    callback();
  }, 3000);
};

const f3 = (callback) => {
  setTimeout(function () {
    console.log("3번 주문 완료");
    callback();
  }, 2000);
};

console.log('시작');
f1(function(){
  f2(function(){
    f3(function(){
      console.log('끝');
    });
  });
});

시작
undefined
VM155:3 1번 주문 완료
VM155:10 2번 주문 완료
VM155:17 3번 주문 완료
VM155:26 끝

// 이렇게 depth가 깊어지면서 callback를 추가하는 것을 callback Hell 콜백지옥이라고 부릅니다. 
```
``` js
// Promise 사용 시
const f1 = () => {
  return new Promise((res, rej) => {
    setTimeout(() => {
      res("1번 주문 완료");
    }, 1000);
  });
};

const f2 = (message) => {
  console.log(message);
  return new Promise((res, rej) => {
    setTimeout(() => {
      res("2번 주문 완료");
    }, 3000);
  });
};

const f3 = (message) => {
  console.log(message);
  return new Promise((res, rej) => {
    setTimeout(() => {
      res("3번 주문 완료");
    }, 2000);
  });
};

// 프로미스 체이닝(Promises chaining)
console.log('시작');
f1()
  .then((res) => f2(res))
  .then((res) => f3(res))
  .then((res) => console.log(res))
  .catch(console.log)
  .finally(() => {
    console.log("끝");
  });
/* "시작" "1번 주문 완료" "2번 주문 완료" "3번 주문 완료" "끝" */
```
``` js
// 2번을 실패로 변경
const f1 = () => {
  return new Promise((res, rej) => {
    setTimeout(() => {
      res("1번 주문 완료");
    }, 1000);
  });
};

const f2 = (message) => {
  console.log(message);
  return new Promise((res, rej) => {
    setTimeout(() => {
      rej("xxx");
    }, 3000);
  });
};

const f3 = (message) => {
  console.log(message);
  return new Promise((res, rej) => {
    setTimeout(() => {
      res("3번 주문 완료");
    }, 2000);
  });
};

console.log('시작');
f1()
  .then((res) => f2(res))
  .then((res) => f3(res))
  .then((res) => console.log(res))
  .catch(console.log)
  .finally(() => {
    console.log("끝");
});
  
  /* "시작" "1번 주문 완료" "xxx" "끝", 3번 실행이 안됨 */  
```
``` js
// Promise.all
const f1 = () => {
  return new Promise((res, rej) => {
    setTimeout(() => {
      res("1번 주문 완료");
    }, 1000);
  });
};

const f2 = (message) => {
  console.log(message);
  return new Promise((res, rej) => {
    setTimeout(() => {
      res("2번 주문 완료");
    }, 3000);
  });
};

const f3 = (message) => {
  console.log(message);
  return new Promise((res, rej) => {
    setTimeout(() => {
      res("3번 주문 완료");
    }, 2000);
  });
};


console.time("x");
Promise.all([f1(), f2(), f3()])
.then((res) => {
  console.log(res);
  console.timeEnd("x");
});

/* undefined undefined ["1번 주문 완료", "2번 주문 완료", "3번 주문 완료"], x: 3002.842041015625 ms undifined는 메시지가 전달된게 없어서 undefined가 나온 것, 원래는 1초 +3초 +2초해서 6초 소요가 되어야 하는데 3초로 변경 됨, 한꺼번에 시작하고 모두 이행되면 값을 사용할 수 있음 */
```
``` js
// Promise.all + f1 rej일때 
const f1 = () => {
  return new Promise((res, rej) => {
    setTimeout(() => {
      rej(new Error("xx"));
    }, 1000);
  });
};

const f2 = (message) => {
  console.log(message);
  return new Promise((res, rej) => {
    setTimeout(() => {
      res("2번 주문 완료");
    }, 3000);
  });
};

const f3 = (message) => {
  console.log(message);
  return new Promise((res, rej) => {
    setTimeout(() => {
      res("3번 주문 완료");
    }, 2000);
  });
};


console.time("x");
Promise.all([f1(), f2(), f3()])
.then((res) => {
  console.log(res);
  console.timeEnd("x");
});

/* undefined undefined Uncaught (in promise) Error : xx
f1을 실패로 바꾸면 실패했다고 뜨고 어떤 데이터도 얻지 못함, 주의해야 함. 
처음에 Promise로 시도했던 방식은 가져온 데이터 순으로 화면을 그릴 수는 있었지만 Promise all은 아님 
하나의 정보라도 누락되면 페이지를 보여주면 안되는 경우 사용할 수 있음, 다 보여주거나 아예 안보여주거나 할 때 쓰는 것 */
```
``` js
// Promise.race, Promise.all과 사용방법이 동일함.

const f1 = () => {
  return new Promise((res, rej) => {
    setTimeout(() => {
      res("1번 주문 완료");
    }, 1000);
  });
};

const f2 = (message) => {
  console.log(message);
  return new Promise((res, rej) => {
    setTimeout(() => {
      rej(new Error("xx"));
    }, 3000);
  });
};

const f3 = (message) => {
  console.log(message);
  return new Promise((res, rej) => {
    setTimeout(() => {
      res("3번 주문 완료");
    }, 2000);
  });
};


console.time("x");
Promise.race([f1(), f2(), f3()])
.then((res) => {
  console.log(res);
  console.timeEnd("x");
});

/* all은 모든 작업이 완료될때까지 기다리지만 race는 말그대로 경주임. 하나라도 1등으로 완료되면 끝냄. 2번이 rej를 예정하고 있었지만 이미 1번이 완료되었기 때문에 무시가 됨, 용량이 큰 이미지들을 로딩하는데 그중에 하나라도 완료되면 그 이미지를 보여줄때 이런 방식을 사용하면 됨 */
```